.TH NINKA 1.3 "May 2015" ninka
.SH NAME
ninka \- source file license identification tool
.SH SYNOPSYS
.SY ninka
.OP \-vfCcSsGgTtLd
.OP \-\-
.RI [ file ]
.YS 

.SH DESCRIPTION

Analyses source files to determine the license they fall under. Takes a source
file as input and outputs the file's license.

.SH OPTIONS

.IP \-v
verbose

.IP \-f
force all processing

.IP \-C
force creation of comments
.IP \-c
stop after creation of comments

.IP \-S
force creation of sentences
.IP \-s
stop after creation of sentences

.IP \-G
force creation of goodsent
.IP \-g
stop after creation of goodsent

.IP \-T
force creation of senttok
.IP \-t
stop after creation of senttok

.IP \-L
force creation of matching

.IP \-d
delete intermediate files

.IP \-\-
Stop processing options

.SH EXAMPLES

.TP
\fBninka\fR \fIfoo.c\fR
Determine the licenses in file foo.c

.TP
.BI ninka\ \-d \ foo.c
Determine the license in file foo.c and delete intermediary files

.TP
find * | xargs \-n1 \-I@ \fBninka\fR '@'
Determine the licenses of files in a directory.


.SH AUTHOR

\fBninka\fR was written by Daniel M. German <dmg@uvic.ca> and Yuki Manabe
<y-manabe@ist.osaka-u.ac.jp>. ninka itself is licensed under the AGPLv3+. This
manpage was written by Ryan Kavanagh <ryanakca@kubuntu.org> for the Debian
project and is also licensed under the AGPLv3+.

.SH SEE ALSO

Daniel M. German, Yuki Manabe and Katsuro Inoue. A sentence-matching method
for automatic license identification of source code files. In 25nd IEEE/ACM
International Conference on Automated Software Engineering (ASE 2010).

You can email Daniel M. German <dmg@uvic.ca> for a copy or download it from
.UR http://turingmachine.org/~dmg/papers/dmg2010ninka.pdf
.UE
